#this is sample

[facebook]
token = "<facebook token>"

[movikuma]
elasticsearch = "https://xxxx"
detail_uri = "https://www.movikuma.tv/m/"
image_uri = "https://xxxx.cloudfront.net/m/"

[ybi]
endpoint = "http://in.ybi.idcfcloud.net/postback/v3/event/<db>/<table>"
apikey = "<Write-Only API keys>"
